name: ticksy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  buttons_tabbar: ^1.3.15
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.0
  http: ^1.5.0
  image_picker: ^1.2.0
  modal_bottom_sheet: ^3.0.0
  stomp_dart_client: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
